### ISSUE TITLE
About identifying license plates or people

### ISSUE THREAD

**Issue by Ruanmeng1** [jullevistrunz/ExternalPoliceComputer#1]
Dear ECP author, I was surprised to find that some license plates can be recognized while others cannot be recognized when using ECP. The same goes for Ped, May I ask if there is a problem with my usage? How should I use it?

**Comment by jullevistrunz** [comment]
If you use StopThePed, peds will always be found. Vehicles may not be found after a while of driving and no callout displayed. I don't know how I can create an interval to update the files without crashing GTA, so I have to use the LSPDFR API's onCalloutDisplayed Event.

**Comment by jullevistrunz** [comment]
With version 1.3.2 this problem will no longer exist
