### ISSUE TITLE
Github update

### ISSUE THREAD

**Issue by Michael21107** [jullevistrunz/ExternalPoliceComputer#2]
would be nice to add link to the about, and requirements to the readme.md

**Comment by jullevistrunz** [comment]
The Readme on github is meant for people who want to customize EPC or develop additional features for EPC. 
The requirements can be found on LCPDFR.com and Discord.

**Comment by jullevistrunz** [comment]
But I can add a link to the release

**Comment by Michael21107** [comment]
true, at least the link is nice
