### ISSUE TITLE
2 licenses

### ISSUE THREAD

**Issue by Michael21107** [jullevistrunz/ExternalPoliceComputer#7]
remove one of the licenses

**Comment by Michael21107** [comment]
@jullevistrunz why do u need 2 different licenses?

**Comment by jullevistrunz** [comment]
https://github.com/jullevistrunz/ExternalPoliceComputer?tab=readme-ov-file#license

**Comment by Michael21107** [comment]
gotcha, thanks

**Comment by Michael21107** [comment]
How are the two licenses different?

**Comment by Michael21107** [comment]
How are the two licenses different?

**Comment by jullevistrunz** [comment]
@Michael21107 MIT allows everyone to share their stuff even for money. Eclipse Public License - v 2.0 requires people to disclose the source and use the same license - making it open source too. (At least that's as far as I know - I'm no lawyer)

**Comment by Michael21107** [comment]
According to [this table](https://choosealicense.com/appendix/), EPL v2.0 also allows commercial (for-money) use, and I don't see why someone would need to not provide the source of the JSON files (which MIT allows).
